class Xpath:
    NAME_INPUT = '//label[contains(text(), "Имя")]/following-sibling::input'
    EMAIL_INPUT = '//label[contains(text(), "Email")]/following-sibling::input'
    PASSWORD_INPUT = '//*[@type="password"]'
    REGISTER_LINK = '//a[@class="Auth_link__1fOlj"]'
    ERROR_MESSAGE = '//*[contains(text(), "Некорректный пароль")]'
    LOG_IN = '//button[text()="Войти в аккаунт"]'
    REGISTER_BUTTON = '//button[text()="Зарегистрироваться"]'
    PERSONAL_ACCOUNT = '//p[contains(text(), "Личный Кабинет")]'
    LOG_OUT = '//button[text()="Выход"]'
    SHORT_LOG_IN = '//button[text()="Войти"]'
    SUPER_SHORT_LOG_IN = '//*[contains(text(), "Вход")]'
    SAUCESS_BUTTON = '//span[text()="Соусы"]'
    ROLLS_BUTTON = '//span[text()="Булки"]'
    TOPPINGS_BUTTON = '//span[text()="Начинки"]'
    CONSTRUCRT = '//*[contains(text(), "Конструктор")]'
    CREAT_BURGER = '//h1[contains(text(), "Соберите бургер")]'
    SAUCESS_STR = '//p[contains(text(), "Соус")]'
    ROLLS_STR = '//p[contains(text(), "булка")]'
    TOPPINGS_STR = '//p[contains(text(), "Мясо")]'
