class Xpath:
    NAME_INPUT = '//label[contains(text(), "Имя")]/following-sibling::input'
    EMAIL_INPUT = '//label[contains(text(), "Email")]/following-sibling::input'
    PASSWORD_INPUT = '//*[@type="password"]'
    REGISTER_LINK = '//a[@class="Auth_link__1fOlj"]'
    ERROR_MESSAGE = '//*[contains(text(), "Некорректный пароль")]'
    LOG_IN = '//button[text()="Войти в аккаунт"]'
    REGISTER_BUTTON = '//button[text()="Зарегистрироваться"]'
    PERSONAL_ACCOUNT = '//p[contains(text(), "Личный Кабинет")]'
    LOG_OUT = '//button[text()="Выход"]'
    SHORT_LOG_IN = '//button[text()="Войти"]'
    SUPER_SHORT_LOG_IN = '//*[contains(text(), "Вход")]'
